defmodule Conjure.Backend.C do
  @moduledoc """
  C backend: compiles LLM-generated C code as a Zigler easy_c NIF.

  The LLM returns return_type, param_types, and source. Conjure generates
  the header itself from those fields — eliminating the fn_name/header mismatch
  that caused retries. The entry function is always named `run`.
  """

  alias Conjure.Store

  def compile(raw, mod, _arity, description, lang) do
    with {:ok, payload}     <- parse_json(raw),
         {:ok, return_type} <- fetch(payload, "return_type"),
         {:ok, param_types} <- fetch(payload, "param_types"),
         {:ok, source_c}    <- fetch(payload, "source") do

      header = build_header(return_type, param_types)

      slug   = Store.slug(description, lang)
      dir    = Path.join([File.cwd!(), "lib", "conjure", "generated", "c"])
      h_path = Path.join(dir, "#{slug}.h")
      c_path = Path.join(dir, "#{slug}.c")

      File.mkdir_p!(dir)
      File.write!(h_path, header)
      File.write!(c_path, source_c <> "\n")

      # Runtime version uses absolute paths (Code.compile_string has no __DIR__)
      source_ex_runtime = module_source(mod, h_path, c_path, dir, description)

      # Saved version uses __DIR__ so the file works when the project moves
      source_ex_saved = module_source_portable(mod, slug, description)

      case safe_compile(source_ex_runtime) do
        :ok ->
          {:ok, source_ex_saved}

        {:error, reason} ->
          File.rm(h_path)
          File.rm(c_path)
          {:error, reason}
      end
    end
  end

  defp build_header(return_type, param_types) do
    params =
      param_types
      |> Enum.with_index()
      |> Enum.map_join(", ", fn {type, i} -> "#{type} arg#{i}" end)

    "#{return_type} run(#{params});\n"
  end

  defp module_source(mod, h_path, c_path, dir, description) do
    """
    defmodule #{inspect(mod)} do
      @moduledoc "#{description} (c code generated by Conjure)"

      def __conjure__(:description), do: "#{description}"
      def __conjure__(:lang),        do: :c

      use Zig,
        otp_app: :conjure,
        easy_c: "#{h_path}",
        c: [src: "#{c_path}", include_dirs: ["#{dir}"]],
        nifs: [run: []]
    end
    """
  end

  defp module_source_portable(mod, slug, description) do
    """
    defmodule #{inspect(mod)} do
      @moduledoc "#{description} (c code generated by Conjure)"

      def __conjure__(:description), do: "#{description}"
      def __conjure__(:lang),        do: :c

      use Zig,
        otp_app: :conjure,
        easy_c: Path.join(__DIR__, "#{slug}.h"),
        c: [src: Path.join(__DIR__, "#{slug}.c"), include_dirs: [__DIR__]],
        nifs: [run: []]
    end
    """
  end

  defp safe_compile(source) do
    Code.compile_string(source)
    :ok
  rescue
    e -> {:error, Exception.message(e)}
  catch
    kind, reason -> {:error, "#{kind}: #{inspect(reason)}"}
  end

  defp parse_json(raw) do
    cleaned =
      raw
      |> String.replace(~r/^```(?:json)?\n?/m, "")
      |> String.replace(~r/\n?```$/m, "")
      |> String.trim()

    case Jason.decode(cleaned) do
      {:ok, map}       -> {:ok, map}
      {:error, reason} -> {:error, "JSON parse failed: #{inspect(reason)}"}
    end
  end

  defp fetch(map, key) do
    case Map.fetch(map, key) do
      {:ok, val} -> {:ok, val}
      :error     -> {:error, "missing key: #{key}"}
    end
  end
end
