defmodule Conjure.Backend.Elixir do
  @moduledoc """
  Elixir backend: the LLM returns named function definitions (def run/N + optional defp helpers).
  We wrap them in a defmodule and compile with Code.compile_string/1.
  """

  def compile(raw, mod, arity, description, _lang) do
    arg_names = Conjure.Prompt.arg_names(arity)
    args_str  = Enum.join(arg_names, ", ")

    # The prompt ends with `def run(...) do` as a completion anchor —
    # the model returns the rest. Reconstruct the full function.
    fns =
      raw
      |> strip_fences()
      |> then(fn body ->
        if String.starts_with?(String.trim(body), "def ") do
          # model returned the full function anyway
          body
        else
          "def run(#{args_str}) do\n#{body}"
        end
      end)

    source = """
    defmodule #{inspect(mod)} do
      @moduledoc "#{description} (elixir code generated by Conjure)"

    #{fns}

      def __conjure__(:description), do: "#{description}"
      def __conjure__(:lang),        do: :elixir

    end
    """

    with :ok <- safe_compile(source) do
      if function_exported?(mod, :run, arity) do
        {:ok, source}
      else
        {:error, "compiled successfully but def run/#{arity} is missing — the model must define `def run(#{Enum.join(Conjure.Prompt.arg_names(arity), ", ")})` as the entry point"}
      end
    end
  end

  defp safe_compile(source) do
    Code.compile_string(source)
    :ok
  rescue
    e -> {:error, Exception.message(e)}
  catch
    kind, reason -> {:error, "#{kind}: #{inspect(reason)}"}
  end

  defp strip_fences(raw) do
    raw
    |> String.replace(~r/^```(?:elixir)?\n?/m, "")
    |> String.replace(~r/\n?```$/m, "")
    |> String.trim()
  end
end
