defmodule Conjure.Backend.Zig do
  @moduledoc """
  Zig backend: compiles LLM-generated Zig code as a Zigler NIF via Code.compile_string/1.

  The LLM returns JSON with fn_code and return_type. The entry function is
  always named `run` — no fn_name negotiation needed.
  """

  def compile(raw, mod, _arity, description, _lang) do
    with {:ok, payload} <- parse_json(raw),
         {:ok, fn_code} <- fetch(payload, "fn_code"),
         {:ok, _ret}    <- fetch(payload, "return_type") do

      source = """
      defmodule #{inspect(mod)} do
        @moduledoc "#{description} (zig code generated by Conjure)"

        use Zig, otp_app: :conjure, nifs: [run: []]

        ~Z\"\"\"
        #{fn_code}
        \"\"\"

        def __conjure__(:description), do: "#{description}"
        def __conjure__(:lang),        do: :zig
      end
      """

      case safe_compile(source) do
        :ok              -> {:ok, source}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  defp safe_compile(source) do
    Code.compile_string(source)
    :ok
  rescue
    e -> {:error, Exception.message(e)}
  catch
    kind, reason -> {:error, "#{kind}: #{inspect(reason)}"}
  end

  defp parse_json(raw) do
    cleaned =
      raw
      |> String.replace(~r/^```(?:json)?\n?/m, "")
      |> String.replace(~r/\n?```$/m, "")
      |> String.trim()

    case Jason.decode(cleaned) do
      {:ok, map}       -> {:ok, map}
      {:error, reason} -> {:error, "JSON parse failed: #{inspect(reason)}"}
    end
  end

  defp fetch(map, key) do
    case Map.fetch(map, key) do
      {:ok, val} -> {:ok, val}
      :error     -> {:error, "missing key: #{key}"}
    end
  end
end
